"""Added rating and rating_count to Worker and Job models

Revision ID: 5e4e810edd9f
Revises: 
Create Date: 2024-10-21 11:19:23.555165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e4e810edd9f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('rating_count', sa.Integer(), nullable=True))

    with op.batch_alter_table('worker', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('rating_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('worker', schema=None) as batch_op:
        batch_op.drop_column('rating_count')
        batch_op.drop_column('rating')

    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.drop_column('rating_count')
        batch_op.drop_column('rating')

    # ### end Alembic commands ###
